import {Inter, Poppins} from "next/font/google"; //importing the fonts 
import "./globals.css";
import Navbar from "./components/Navbar";
import Landingpage from "./pages";


const inter= Inter({subsets: ['latin']});
//defined the font here 
const poppins = Poppins({
  subsets:['latin'],
  variable:'--font-poppins',
  weight:['100','200','300','400','500','600','700','800','900'],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Quiz</title>
      </head>
      <body className="font-poppins h-screen overflow-hidden">
        <header className="h-auto">
          <Navbar />
        </header>
        <main className="h-full">
          <Landingpage /> {/* Your landing page will be displayed here without scrolling */}
          {children}
        </main>
      </body>
    </html>
  );
}

